var websites = [
							  { Category: "Website",
                  Link: 'https://www.behance.net/gallery/56636523/Portfolio-2017-v2',
                  ProjectName: "Portfolio 2017 v2",
                  Year: '2017',
                  Link0: "https://www.behance.net/gallery/56636523/Portfolio-2017-v2",
                  Link1: "https://github.com/berkekiran/portfolio-2017-v2",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2017-v2.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/c69f2456636523.59b6d5ef3be53.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55791649/Portfolio-2016-v2',
                  ProjectName: 'Portfolio 2017',
                  Year: '2017',
                  Link0: "https://www.behance.net/gallery/55844571/Portfolio-2017",
                  Link1: "https://github.com/berkekiran/portfolio-2017",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2017.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/fs/f0f0d755844571.59957ded498a7.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55791649/Portfolio-2016-v2',
                  ProjectName: 'Portfolio 2016 v2',
                  Year: '2016',
                  Link0: "https://www.behance.net/gallery/55791649/Portfolio-2016-v2",
                  Link1: "https://github.com/berkekiran/portfolio-2016-v2",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2016-v2.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/cdc09055791649.5993654db84a4.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55790661/Video-Games-Center-Station',
                  ProjectName: 'Video Games CS',
                  Year: '2016',
                  Link0: "https://www.behance.net/gallery/55790661/Video-Games-Center-Station",
                  Link1: "https://github.com/berkekiran/video-games-center-station",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/video-games-center-station.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/04aa1355790661.59935d185a7dd.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55771277/Portfolio-2016',
                  ProjectName: 'Portfolio 2016',
                  Year: '2016',
                  Link0: "https://www.behance.net/gallery/55771277/Portfolio-2016",
                  Link1: "https://github.com/berkekiran/portfolio-2016",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2016.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/1bc49055771277.5992c282f15f0.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55754747/Portfolio-2015-v5',
                  ProjectName: 'Portfolio 2015 v5',
                  Year: '2015',
                  Link0: "https://www.behance.net/gallery/55754747/Portfolio-2015-v5",
                  Link1: "",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2015-v5.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/aef4b955754747.599203545286e.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55752371/Portfolio-2015-v4',
                  ProjectName: 'Portfolio 2015 v4',
                  Year: '2015',
                  Link0: "https://www.behance.net/gallery/55752371/Portfolio-2015-v4",
                  Link1: "https://github.com/berkekiran/portfolio-2015-v5",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2015-v4.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/a916da55752371.5991fd8e882e8.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55748605/Portfolio-2015-v3-Design',
                  ProjectName: 'Portfolio 2015 v3',
                  Year: '2015',
                  Link0: "https://www.behance.net/gallery/55748605/Portfolio-2015-v3-Design",
                  Link1: "",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2015-v3-design.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/28699b55748605.5991d45a2220b.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55747869/Portfolio-2015-v2-Design',
                  ProjectName: 'Portfolio 2015 v2',
                  Year: '2015',
                  Link0: "https://www.behance.net/gallery/55747869/Portfolio-2015-v2-Design",
                  Link1: "https://github.com/berkekiran/portfolio-2015-v4",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2015-v2-design.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/cfa60955747869.5991cdd8f2575.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55742749/Portfolio-2015',
                  ProjectName: 'Portfolio 2015',
                  Year: '2015',
                  Link0: "https://www.behance.net/gallery/55742749/Portfolio-2015",
                  Link1: "https://github.com/berkekiran/portfolio-2015",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/portfolio-2015.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/54beff55742749.5991a4c36df38.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Website",
                  Link: 'https://www.behance.net/gallery/55738571/Photo-Galleries',
                  ProjectName: 'Photo Galleries',
                  Year: '2014',
                  Link0: "https://www.behance.net/gallery/55738571/Photo-Galleries",
                  Link1: "https://github.com/berkekiran/quick-write",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/photo-galleries.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/085b1c55738571.59917f5560ae0.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
                { Category: "Silverlight Project",
                  Link: 'https://www.behance.net/gallery/55736987/Quick-Write',
                  ProjectName: 'Quick Write',
                  Year: '2013',
                  Link0: "https://www.behance.net/gallery/55736987/Quick-Write",
                  Link1: "https://github.com/berkekiran/photo-galleries",
                  Link0Image: {"background" : "url('images/behance.png')", "background-position" : "center", "background-repeat" : "no-repeat", "background-size" : "74%"},
                  Link1Image: {"background" : "url('images/github.png')", "background-size" : "74%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Logo: {"background" : " url('images/other-projects/quick-write.png')", "background-size" : "200%", "background-position" : "center", "background-repeat" : "no-repeat"},
                  Image: {"background" : " url('https://mir-s3-cdn-cf.behance.net/project_modules/1400/1ddf4855736987.599178c3362b3.png')", "background-size" : "cover", "background-position" : "center top", "background-repeat" : "no-repeat"} },
             ];
